[package]
name = "goban"
version = "0.1.0"
authors = ["Devin Jacobs <dbuttonz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.7.0-alpha.1"
features = ["extension-module"]

[dependencies]
